//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тест.file
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комнаты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Комнаты()
        {
            this.Клиенты = new HashSet<Клиенты>();
        }
    
        public int Номер { get; set; }
        public int КодКатегории { get; set; }
        public int КодЭтажа { get; set; }
        public int КодСтатуса { get; set; }
    
        public virtual Категории Категории { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Клиенты> Клиенты { get; set; }
        public virtual Статусы Статусы { get; set; }
        public virtual Этажи Этажи { get; set; }
    }
}
