//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тест.file
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int Код { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int Роль { get; set; }
        public bool Блокировка { get; set; }
        public int ПопыткаВхода { get; set; }
        public Nullable<System.DateTime> ПоследняяПопыткаВхода { get; set; }
        public bool ТребуетсяСменаПароля { get; set; }
    
        public virtual Роли Роли { get; set; }
    }
}
